title: SmarietVan 的冒险日志
description: 一位冒险者在代码大陆上的旅途见闻
url: https://smarietvan.github.io
lang: zh-CN

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
